/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UTS_A.View;

/**
 *
 * @author ASUS
 */
public class FormPelanggan extends javax.swing.JPanel {

    /**
     * Creates new form FormPelanggan
     */
    public FormPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(null);

        jLabel1.setText("                                                                                                                                                                                                                                                   ");
        add(jLabel1);
        jLabel1.setBounds(446, 9, 729, 16);

        jLabel2.setText("Nama");
        add(jLabel2);
        jLabel2.setBounds(15, 37, 32, 16);

        jLabel3.setText("Meter Bulan Ini");
        add(jLabel3);
        jLabel3.setBounds(15, 65, 80, 16);

        jLabel4.setText("Meter Bulan Lalu");
        add(jLabel4);
        jLabel4.setBounds(15, 93, 89, 16);

        jLabel5.setText("Kode Pelanggan");
        add(jLabel5);
        jLabel5.setBounds(15, 9, 86, 16);

        jLabel6.setText("Tarif");
        add(jLabel6);
        jLabel6.setBounds(15, 121, 23, 16);

        jLabel7.setText("Diskon");
        add(jLabel7);
        jLabel7.setBounds(15, 149, 36, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(175, 6, 265, 22);
        add(jTextField2);
        jTextField2.setBounds(175, 34, 265, 22);
        add(jTextField3);
        jTextField3.setBounds(175, 62, 265, 22);
        add(jTextField4);
        jTextField4.setBounds(175, 90, 265, 22);
        add(jTextField5);
        jTextField5.setBounds(175, 118, 265, 22);
        add(jTextField6);
        jTextField6.setBounds(175, 146, 265, 22);

        jButton1.setText("Insert");
        add(jButton1);
        jButton1.setBounds(51, 174, 72, 23);

        jButton2.setText("Update");
        add(jButton2);
        jButton2.setBounds(175, 174, 72, 23);

        jButton3.setText("Delete");
        add(jButton3);
        jButton3.setBounds(295, 174, 72, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "MBI", "MBL", "Tarif", "Diskon", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 430, 210);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
